### ISSUE TITLE
cannot shut down from UI

### ISSUE THREAD

**Issue by gearhead** [gearhead/RuneUI#20]
When I attempt a shutdown or reboot from the UI, I get this in the log and it will not shut down:

Nov 23 08:34:04 runeaudio rune_SY_wrk[1560]: Fatal error: Uncaught RedisException: Connection refused in /srv/http/app/libs/runeaudio.php:1323
Nov 23 08:34:04 runeaudio rune_SY_wrk[1560]: Stack trace:
Nov 23 08:34:04 runeaudio rune_SY_wrk[1560]: #0 /srv/http/app/libs/runeaudio.php(1323): Redis->connect('127.0.0.1', 6379)
Nov 23 08:34:04 runeaudio rune_SY_wrk[1560]: #1 /srv/http/app/libs/runeaudio.php(775): runelog('sysCmd($str)', 'chmod 777 /run')
Nov 23 08:34:04 runeaudio rune_SY_wrk[1560]: #2 /srv/http/command/rune_SY_wrk(51): sysCmd('chmod 777 /run')
Nov 23 08:34:04 runeaudio rune_SY_wrk[1560]: #3 {main}
Nov 23 08:34:04 runeaudio rune_SY_wrk[1560]:   thrown in /srv/http/app/libs/runeaudio.php on line 1323

I noted that runeaudio.php references port 6379 instead of socket /run/redis/socket. In redis, we have the port turned off. Even when I turn the socket back on and reboot, I still get this error and cannot shut down from the UI.

Lines 1319 to 1323
1319 function runelog($title, $data = null, $function_name = null)
1320 {
1321 // Connect to Redis backend
1322     $store = new Redis();
1323     $store->connect('127.0.0.1', 6379);

**Comment by gearhead** [comment]
Issue can be resolved by updating via git. The fix was to add some lines to redis. Since we are using the 'default' redis package but are using a socket instead of the port, we need to add to the redis.service file. The commit here fixes it:
https://github.com/gearhead/RuneUI/commit/25b22846d10e5e6ebc7f73ee4d2958dd7cae8a54

**Comment by gearhead** [comment]
The commit fixes it. I can now shutdown and restart from the UI. To propagate this fix to the installation, you need to either copy the redis.service file to the correct directory and run 'systemctl daemon-reload' or run the image_reset_script in the command/ directory
